// src/client/lib/components/ArtefactCard.tsx
import { Bookmark, Database, Folder, Link } from "lucide-react";
import type { ArtefactSummary, SetLinkGateRequest } from "../../../shared/contracts";
import { Card } from "$lib/components/ui/card";
import { fmtBytes, kindMeta, relativeTime, STORAGE_LABEL, type DataVisibility, type Visibility } from "../format";
import { hueVars, kindVars } from "../style";
import { cn } from "../utils";
import { CardThumbnail } from "./CardThumbnail";
import { LinkGateBadges } from "./LinkGateBadges";
import { MoreMenu } from "./MoreMenu";
import { VisibilityControl } from "./VisibilityControl";

/** Everything a card or row of an artefact you own needs. */
export interface OwnedItemProps {
  a: ArtefactSummary;
  onOpen: () => void;
  onCopy: () => void;
  onEdit: () => void;
  onArchive: () => void;
  onVisibility: (v: Visibility, linkGate?: { password?: string; expiresAt?: string }) => void;
  // S32a — change the link protection of this (public) artefact.
  onLinkGate?: (change: SetLinkGateRequest) => void;
  onManage: () => void;
  // S41 — whether viewers may load each other's saved data.
  onDataVisibility?: (v: DataVisibility) => void;
  // S25/S27 — collections + bookmarks.
  collectionName?: string | null;
  onOpenCollection?: () => void;
  bookmarked?: boolean;
  onBookmark?: () => void;
  onMoveToCollection?: () => void;
  // Hide the "in <Collection>" chip when the item already sits on that
  // collection's page.
  showCollectionChip?: boolean;
}

export const chip = "inline-flex items-center justify-center rounded-md bg-card p-1 shadow-sm";
export const linkish =
  "inline-flex min-w-0 cursor-pointer items-center gap-1 rounded-sm outline-none hover:underline focus-visible:ring-[3px] focus-visible:ring-ring/50";

/** The owned item's derived bits and its visibility control, shared by card and row. */
export function useOwnedItem(p: OwnedItemProps, variant: "block" | "pill") {
  const { a } = p;
  const inherited = a.collectionId !== null;
  // Link reachability follows the *effective* tier (AH20).
  const isShared = a.effectiveVisibility !== "private" && !!a.publicSlug;
  const visibility = (
    <VisibilityControl
      visibility={a.effectiveVisibility}
      variant={variant}
      onChoose={p.onVisibility}
      onManage={p.onManage}
      inherited={inherited}
      inheritedFrom={p.collectionName ?? ""}
      onOpenCollection={p.onOpenCollection}
      usesStorage={a.usesStorage}
      dataVisibility={a.dataVisibility}
      onChooseData={p.onDataVisibility}
      linkProtection={
        p.onLinkGate
          ? {
              current: a.linkGate ?? null,
              onPublish: (gate) => p.onVisibility("public", gate),
              onSave: p.onLinkGate,
            }
          : undefined
      }
    />
  );
  const menu = (
    <MoreMenu
      isShared={isShared}
      variant={variant === "block" ? "grid" : "list"}
      onOpen={p.onOpen}
      onCopy={p.onCopy}
      onEdit={p.onEdit}
      onArchive={p.onArchive}
      bookmarked={p.bookmarked}
      onBookmark={p.onBookmark}
      inCollection={inherited}
      onMoveToCollection={p.onMoveToCollection}
      downloadHref={`/api/artefacts/${a.id}/download`}
    />
  );
  const collectionChip = inherited && p.collectionName && p.showCollectionChip !== false && (
    <button
      type="button"
      onClick={p.onOpenCollection}
      title={`Open “${p.collectionName}”`}
      style={hueVars(a.collectionId!)}
      className={cn(linkish, "max-w-36")}
    >
      <Folder className="size-3 shrink-0 text-(--hue)" />
      <span className="truncate">in {p.collectionName}</span>
    </button>
  );
  const shareLink = isShared && (
    <button type="button" onClick={p.onCopy} title={`Copy ${location.origin}/a/${a.publicSlug}`} className={cn(linkish, "text-primary")}>
      <Link className="size-3" />
      <span className="font-mono">/a/{a.publicSlug}</span>
    </button>
  );
  return { isShared, visibility, menu, collectionChip, shareLink };
}

export const Dot = () => <span className="opacity-50">·</span>;

// A grid card of an artefact you own.
export function ArtefactCard(p: OwnedItemProps) {
  const { a } = p;
  const { visibility, menu, collectionChip, shareLink } = useOwnedItem(p, "block");
  return (
    <Card className="gap-0 overflow-hidden py-0 shadow-xs">
      <CardThumbnail
        kind={a.kind}
        title={a.title}
        thumbnailUrl={a.thumbnailUrl}
        onOpen={p.onOpen}
        chips={
          <>
            {p.bookmarked && (
              <span title="Bookmarked" aria-label="Bookmarked" className={cn(chip, "text-primary")}>
                <Bookmark className="size-3.5 fill-current" />
              </span>
            )}
            <LinkGateBadges gate={a.linkGate} variant="chip" />
            {a.usesStorage && (
              <span title={STORAGE_LABEL} aria-label={STORAGE_LABEL} className={cn(chip, "text-muted-foreground")}>
                <Database className="size-3.5" />
              </span>
            )}
          </>
        }
      />
      <div className="flex flex-col gap-2.5 p-3.5 pt-3">
        <div className="flex items-start gap-2">
          <button
            type="button"
            onClick={p.onOpen}
            className="min-w-0 flex-1 cursor-pointer truncate rounded-sm text-left text-sm leading-snug font-semibold outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50"
          >
            {a.title}
          </button>
          {menu}
        </div>
        {visibility}
        <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
          {collectionChip && (
            <>
              {collectionChip}
              <Dot />
            </>
          )}
          <span>Updated {relativeTime(a.updatedAt)}</span>
          <Dot />
          <span className="font-mono">{fmtBytes(a.payloadBytes)}</span>
          {shareLink && <span className="ml-auto">{shareLink}</span>}
        </div>
      </div>
    </Card>
  );
}

// A list row of an artefact you own.
export function ArtefactRow(p: OwnedItemProps) {
  const { a } = p;
  const m = kindMeta(a.kind);
  const Icon = m.icon;
  const { visibility, menu, collectionChip, shareLink } = useOwnedItem(p, "pill");
  return (
    <Card className="flex-row items-center gap-3.5 px-3.5 py-2.5 shadow-xs">
      <button
        type="button"
        onClick={p.onOpen}
        aria-label={`Open ${a.title}`}
        style={kindVars(a.kind)}
        className="flex size-10 shrink-0 cursor-pointer items-center justify-center rounded-lg bg-(--kind-tint) outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50"
      >
        <Icon className="size-5 text-(--kind)" strokeWidth={1.7} />
      </button>
      <div className="min-w-0 flex-1">
        <button
          type="button"
          onClick={p.onOpen}
          className="block max-w-full cursor-pointer truncate rounded-sm text-left text-sm font-semibold outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50"
        >
          {a.title}
          {p.bookmarked && <Bookmark className="ml-1.5 inline size-3 fill-current align-[-1px] text-primary" />}
        </button>
        <div className="mt-0.5 flex flex-wrap items-center gap-1.5 text-xs text-muted-foreground">
          <span>{m.label}</span>
          {collectionChip && (
            <>
              <Dot />
              {collectionChip}
            </>
          )}
          <LinkGateBadges gate={a.linkGate} variant="inline" />
          {a.usesStorage && (
            <span title={STORAGE_LABEL} aria-label={STORAGE_LABEL} className="inline-flex items-center">
              <Database className="size-3" />
            </span>
          )}
          <Dot />
          <span>Updated {relativeTime(a.updatedAt)}</span>
          <Dot />
          <span className="font-mono">{fmtBytes(a.payloadBytes)}</span>
          {shareLink && (
            <>
              <Dot />
              {shareLink}
            </>
          )}
        </div>
      </div>
      {visibility}
      {menu}
    </Card>
  );
}

// src/client/lib/components/ArtefactCard.svelte
<script lang="ts">
  import type { ArtefactSummary, SetLinkGateRequest } from "../../../shared/contracts";
  import {
    fmtBytes,
    relativeTime,
    collectionColor,
    BOOKMARK_ICON,
    FOLDER_ICON,
    STORAGE_ICON,
    STORAGE_LABEL,
    type DataVisibility,
    type Visibility,
  } from "../format";
  import { overlay } from "../ui.svelte";
  import Icon from "./Icon.svelte";
  import CardThumbnail from "./CardThumbnail.svelte";
  import MoreMenu from "./MoreMenu.svelte";
  import VisibilityControl from "./VisibilityControl.svelte";
  import LinkGateBadges from "./LinkGateBadges.svelte";

  interface Props {
    a: ArtefactSummary;
    onOpen: () => void;
    onCopy: () => void;
    onEdit: () => void;
    onArchive: () => void;
    onVisibility: (v: Visibility, linkGate?: { password?: string; expiresAt?: string }) => void;
    // S32a — change the link protection of this (public) artefact.
    onLinkGate?: (change: SetLinkGateRequest) => void;
    onManage: () => void;
    // S41 — whether viewers may load each other's saved data.
    onDataVisibility?: (v: DataVisibility) => void;
    // S25/S27 — collections + bookmarks.
    collectionName?: string | null;
    onOpenCollection?: () => void;
    bookmarked?: boolean;
    onBookmark?: () => void;
    onMoveToCollection?: () => void;
    // Hide the "in <Collection>" chip when the card already sits on that
    // collection's page.
    showCollectionChip?: boolean;
  }
  let {
    a,
    onOpen,
    onCopy,
    onEdit,
    onArchive,
    onVisibility,
    onLinkGate,
    onManage,
    onDataVisibility,
    collectionName = null,
    onOpenCollection,
    bookmarked = false,
    onBookmark,
    onMoveToCollection,
    showCollectionChip = true,
  }: Props = $props();

  const inherited = $derived(a.collectionId !== null);
  // Link reachability follows the *effective* tier (AH20).
  const isShared = $derived(a.effectiveVisibility !== "private" && !!a.publicSlug);
  const raised = $derived(
    overlay.isOpen(`menu:${a.id}`) || overlay.isOpen(`vis:${a.id}`),
  );
</script>

<!-- Grid card: base look + hover "pop" come from `.af-card-grid` (app.css). When a
     menu/visibility picker is open the card is raised above neighbours (z 50, beating
     the hover z 20) so the dropdown isn't clipped. -->
<div class="af-card-grid" style={raised ? "z-index:50;" : ""}>
  <CardThumbnail kind={a.kind} title={a.title} thumbnailUrl={a.thumbnailUrl} {onOpen}>
    {#snippet chips()}
      {#if bookmarked}
        <span
          title="Bookmarked"
          aria-label="Bookmarked"
          style="display:inline-flex;align-items:center;justify-content:center;padding:4px;border-radius:7px;background:var(--card);color:var(--primary);box-shadow:var(--shadow);"
        >
          <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2" stroke-linejoin="round">
            <path d={BOOKMARK_ICON[0]} />
          </svg>
        </span>
      {/if}
      <LinkGateBadges gate={a.linkGate} variant="chip" />
      {#if a.usesStorage}
        <span
          title={STORAGE_LABEL}
          aria-label={STORAGE_LABEL}
          style="display:inline-flex;align-items:center;justify-content:center;padding:4px;border-radius:7px;background:var(--card);color:var(--muted-fg);box-shadow:var(--shadow);"
        >
          <Icon paths={STORAGE_ICON} size={13} width={1.8} />
        </span>
      {/if}
    {/snippet}
  </CardThumbnail>

  <!-- body -->
  <div style="padding:13px 14px 12px;display:flex;flex-direction:column;gap:10px;">
    <div style="display:flex;align-items:flex-start;gap:8px;">
      <button
        onclick={onOpen}
        style="flex:1;min-width:0;text-align:left;background:none;border:none;padding:0;cursor:pointer;font-family:inherit;color:var(--fg);font-size:14px;font-weight:600;letter-spacing:-0.01em;line-height:1.3;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;"
      >
        {a.title}
      </button>
      <MoreMenu
        id={a.id}
        {isShared}
        variant="grid"
        {onOpen}
        {onCopy}
        {onEdit}
        {onArchive}
        {bookmarked}
        {onBookmark}
        inCollection={inherited}
        {onMoveToCollection}
        downloadHref="/api/artefacts/{a.id}/download"
      />
    </div>

    <VisibilityControl
      id={a.id}
      visibility={a.effectiveVisibility}
      variant="block"
      onChoose={onVisibility}
      {onManage}
      {inherited}
      inheritedFrom={collectionName ?? ""}
      {onOpenCollection}
      usesStorage={a.usesStorage}
      dataVisibility={a.dataVisibility}
      onChooseData={onDataVisibility}
      linkProtection={onLinkGate
        ? {
            current: a.linkGate ?? null,
            onPublish: (gate) => onVisibility("public", gate),
            onSave: onLinkGate,
          }
        : undefined}
    />

    <!-- footer meta -->
    <div style="display:flex;align-items:center;gap:8px;font-size:11.5px;color:var(--muted-fg);flex-wrap:wrap;">
      {#if inherited && collectionName && showCollectionChip}
        <button
          onclick={onOpenCollection}
          title={`Open “${collectionName}”`}
          style="display:inline-flex;align-items:center;gap:4px;max-width:130px;background:none;border:none;padding:0;cursor:pointer;font-family:inherit;font-size:11.5px;color:var(--muted-fg);"
        >
          <Icon paths={FOLDER_ICON} size={11} width={1.8} color={collectionColor(a.collectionId!)} style="flex-shrink:0;" />
          <span style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">in {collectionName}</span>
        </button>
        <span style="opacity:.5;">·</span>
      {/if}
      <span>Updated {relativeTime(a.updatedAt)}</span>
      <span style="opacity:.5;">·</span>
      <span style="font-family:'Geist Mono',monospace;">{fmtBytes(a.payloadBytes)}</span>
      {#if isShared}
        <button
          onclick={onCopy}
          title={`Copy ${location.origin}/a/${a.publicSlug}`}
          style="margin-left:auto;display:inline-flex;align-items:center;gap:4px;color:var(--primary);background:none;border:none;padding:0;cursor:pointer;font-family:inherit;"
        >
          <Icon
            paths={[
              "M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-1 1",
              "M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l1-1",
            ]}
            size={12}
          />
          <span style="font-family:'Geist Mono',monospace;font-size:11px;">/a/{a.publicSlug}</span>
        </button>
      {/if}
    </div>
  </div>
</div>
