// src/client/lib/components/LinkProtection.svelte
<script lang="ts">
  import type { LinkGateSummary } from "../../../shared/contracts";
  import {
    EXPIRY_CHOICES,
    copyText,
    enablePassword,
    formError,
    formFor,
    type LinkProtectionForm,
  } from "../link-protection";
  import Icon from "./Icon.svelte";

  // S32a — the "Link protection" section of the visibility picker: a password
  // and/or an expiry on a public link. `publish` rides along with the change to
  // Public; `edit` changes the gate of an artefact that is already public.
  interface Props {
    mode: "publish" | "edit";
    current?: LinkGateSummary | null;
    submitLabel: string;
    onSubmit: (form: LinkProtectionForm) => void;
    onCancel: () => void;
  }
  let { mode, current = null, submitLabel, onSubmit, onCancel }: Props = $props();

  // Seeded once from the gate being edited; the owner's edits live here after.
  // svelte-ignore state_referenced_locally
  let form = $state<LinkProtectionForm>(formFor(mode === "edit" ? current : null));
  let copyLabel = $state<"Copy" | "Copied" | "Copy failed">("Copy");
  let copyTimer: ReturnType<typeof setTimeout> | undefined;

  const error = $derived(formError(form, new Date()));
  const LOCK = ["M5 11h14v10H5z", "M8 11V7a4 4 0 0 1 8 0v4"];
  const CLOCK = ["M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20z", "M12 6v6l4 2"];
  const COPY = ["M9 9h11v11H9z", "M5 15H4V4h11v1"];

  function togglePassword(on: boolean) {
    form = on ? enablePassword(form) : { ...form, requirePassword: false, keepPassword: false };
  }

  async function copy() {
    copyLabel = await copyText(navigator.clipboard, form.password);
    clearTimeout(copyTimer);
    copyTimer = setTimeout(() => (copyLabel = "Copy"), 1600);
  }

  function fmtDate(iso: string): string {
    return new Date(iso).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });
  }

  const label =
    "display:block;font-size:10.5px;font-weight:600;text-transform:uppercase;letter-spacing:0.04em;color:var(--muted-fg);";
  const input =
    "width:100%;height:30px;padding:0 8px;border:1px solid var(--border);background:var(--card);color:var(--fg);border-radius:7px;font-size:12px;font-family:inherit;outline:none;";
  const small =
    "height:26px;padding:0 9px;border:1px solid var(--border);background:var(--card);color:var(--fg);border-radius:7px;font-size:11.5px;font-weight:500;cursor:pointer;font-family:inherit;white-space:nowrap;";
</script>

<div style="display:flex;flex-direction:column;gap:10px;padding:8px 9px 6px;">
  <span style={label}>Link protection</span>

  <!-- password -->
  <div style="display:flex;flex-direction:column;gap:6px;">
    {#if form.keepPassword}
      <div style="display:flex;align-items:center;gap:6px;font-size:12px;">
        <Icon paths={LOCK} size={13} />
        <span style="flex:1;">Password set</span>
        <button style={small} onclick={() => togglePassword(true)}>Change</button>
        <button style={small} onclick={() => togglePassword(false)}>Clear</button>
      </div>
    {:else}
      <label style="display:flex;align-items:center;gap:7px;font-size:12px;cursor:pointer;">
        <input
          type="checkbox"
          checked={form.requirePassword}
          onchange={(e) => togglePassword(e.currentTarget.checked)}
        />
        Require a password
      </label>
      {#if form.requirePassword}
        <div style="display:flex;gap:6px;">
          <input
            type="text"
            bind:value={form.password}
            aria-label="Link password"
            autocomplete="off"
            spellcheck="false"
            style="{input}font-family:'Geist Mono',monospace;"
          />
          <button style={small} onclick={copy} title="Copy the password">
            <span style="display:inline-flex;align-items:center;gap:4px;">
              <Icon paths={COPY} size={12} />{copyLabel}
            </span>
          </button>
        </div>
        <span style="font-size:11px;color:var(--muted-fg);">
          Share it with the people you send the link to. It is shown only now.
        </span>
      {/if}
    {/if}
  </div>

  <!-- expiry -->
  <div style="display:flex;flex-direction:column;gap:6px;">
    {#if form.keepExpiry}
      <div style="display:flex;align-items:center;gap:6px;font-size:12px;">
        <Icon paths={CLOCK} size={13} />
        <span style="flex:1;">
          {current?.expiresAt ? `Expires ${fmtDate(current.expiresAt)}` : "Never expires"}
        </span>
        <button style={small} onclick={() => (form = { ...form, keepExpiry: false })}>Change</button>
      </div>
    {:else}
      <label style="display:flex;align-items:center;gap:7px;font-size:12px;">
        <span style="flex-shrink:0;">Link expires</span>
        <select bind:value={form.expiry} style="{input}width:auto;flex:1;">
          {#each EXPIRY_CHOICES as choice (choice.value)}
            <option value={choice.value}>{choice.label}</option>
          {/each}
        </select>
      </label>
      {#if form.expiry === "custom"}
        <input type="datetime-local" bind:value={form.customExpiry} aria-label="Expiry" style={input} />
      {/if}
    {/if}
  </div>

  {#if error}
    <span style="font-size:11.5px;color:var(--destructive);">{error}</span>
  {/if}

  <div style="display:flex;justify-content:flex-end;gap:6px;">
    <button style={small} onclick={onCancel}>Cancel</button>
    <button
      disabled={error !== null}
      onclick={() => onSubmit(form)}
      style="{small}border:none;background:var(--primary);color:var(--primary-fg);font-weight:600;opacity:{error
        ? 0.5
        : 1};"
    >
      {submitLabel}
    </button>
  </div>
</div>

// src/client/lib/components/LinkProtection.tsx
import { useEffect, useRef, useState } from "react";
import { Clock, Copy, Lock } from "lucide-react";
import type { LinkGateSummary } from "../../../shared/contracts";
import { Button } from "$lib/components/ui/button";
import { Checkbox } from "$lib/components/ui/checkbox";
import { Input } from "$lib/components/ui/input";
import { Label } from "$lib/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "$lib/components/ui/select";
import {
  EXPIRY_CHOICES,
  copyText,
  enablePassword,
  formError,
  formFor,
  type ExpiryChoice,
  type LinkProtectionForm,
} from "../link-protection";

// S32a — the "Link protection" section of the visibility picker: a password
// and/or an expiry on a public link. `publish` rides along with the change to
// Public; `edit` changes the gate of an artefact that is already public.
export function LinkProtection({
  mode,
  current = null,
  submitLabel,
  onSubmit,
  onCancel,
}: {
  mode: "publish" | "edit";
  current?: LinkGateSummary | null;
  submitLabel: string;
  onSubmit: (form: LinkProtectionForm) => void;
  onCancel: () => void;
}) {
  // Seeded once from the gate being edited; the owner's edits live here after.
  const [form, setForm] = useState<LinkProtectionForm>(() => formFor(mode === "edit" ? current : null));
  const [copyLabel, setCopyLabel] = useState<"Copy" | "Copied" | "Copy failed">("Copy");
  const copyTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  useEffect(() => () => clearTimeout(copyTimer.current), []);

  const error = formError(form, new Date());

  function togglePassword(on: boolean) {
    setForm(on ? enablePassword(form) : { ...form, requirePassword: false, keepPassword: false });
  }

  async function copy() {
    setCopyLabel(await copyText(navigator.clipboard, form.password));
    clearTimeout(copyTimer.current);
    copyTimer.current = setTimeout(() => setCopyLabel("Copy"), 1600);
  }

  const fmtDate = (iso: string) =>
    new Date(iso).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });

  return (
    <div className="flex flex-col gap-3 p-2">
      <span className="text-xs font-semibold tracking-wide text-muted-foreground uppercase">Link protection</span>

      <div className="flex flex-col gap-2">
        {form.keepPassword ? (
          <div className="flex items-center gap-2 text-sm">
            <Lock className="size-3.5" />
            <span className="flex-1">Password set</span>
            <Button variant="outline" size="sm" onClick={() => togglePassword(true)}>
              Change
            </Button>
            <Button variant="outline" size="sm" onClick={() => togglePassword(false)}>
              Clear
            </Button>
          </div>
        ) : (
          <>
            <Label className="flex cursor-pointer items-center gap-2 font-normal">
              <Checkbox checked={form.requirePassword} onCheckedChange={(v) => togglePassword(v === true)} />
              Require a password
            </Label>
            {form.requirePassword && (
              <>
                <div className="flex gap-1.5">
                  <Input
                    value={form.password}
                    onChange={(e) => setForm({ ...form, password: e.target.value })}
                    aria-label="Link password"
                    autoComplete="off"
                    spellCheck={false}
                    className="h-8 font-mono"
                  />
                  <Button variant="outline" size="sm" onClick={copy} title="Copy the password">
                    <Copy />
                    {copyLabel}
                  </Button>
                </div>
                <span className="text-xs text-muted-foreground">
                  Share it with the people you send the link to. It is shown only now.
                </span>
              </>
            )}
          </>
        )}
      </div>

      <div className="flex flex-col gap-2">
        {form.keepExpiry ? (
          <div className="flex items-center gap-2 text-sm">
            <Clock className="size-3.5" />
            <span className="flex-1">
              {current?.expiresAt ? `Expires ${fmtDate(current.expiresAt)}` : "Never expires"}
            </span>
            <Button variant="outline" size="sm" onClick={() => setForm({ ...form, keepExpiry: false })}>
              Change
            </Button>
          </div>
        ) : (
          <>
            <div className="flex items-center gap-2 text-sm">
              <span className="shrink-0">Link expires</span>
              <Select value={form.expiry} onValueChange={(v) => setForm({ ...form, expiry: v as ExpiryChoice })}>
                <SelectTrigger size="sm" className="flex-1" aria-label="Link expires">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {EXPIRY_CHOICES.map((choice) => (
                    <SelectItem key={choice.value} value={choice.value}>
                      {choice.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            {form.expiry === "custom" && (
              <Input
                type="datetime-local"
                value={form.customExpiry}
                onChange={(e) => setForm({ ...form, customExpiry: e.target.value })}
                aria-label="Expiry"
                className="h-8"
              />
            )}
          </>
        )}
      </div>

      {error && <span className="text-xs text-destructive">{error}</span>}

      <div className="flex justify-end gap-1.5">
        <Button variant="outline" size="sm" onClick={onCancel}>
          Cancel
        </Button>
        <Button size="sm" disabled={error !== null} onClick={() => onSubmit(form)}>
          {submitLabel}
        </Button>
      </div>
    </div>
  );
}
